// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file api/user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/user/v1/user.proto.
 */
export const file_api_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGkvdXNlci92MS91c2VyLnByb3RvEgd1c2VyLnYxIiwKDVNpZ25JblJlcXVlc3QSDAoEY29kZRgBIAEoCRINCgVzdGF0ZRgCIAEoCSItCg5TaWduSW5SZXNwb25zZRINCgVzdGF0ZRgBIAEoCRIMCgRkYXRhGAIgASgJMkoKC1VzZXJTZXJ2aWNlEjsKBlNpZ25JbhIWLnVzZXIudjEuU2lnbkluUmVxdWVzdBoXLnVzZXIudjEuU2lnbkluUmVzcG9uc2UiAEJ8Cgtjb20udXNlci52MUIJVXNlclByb3RvUAFaJWNvbm5lY3QtZ28tZXhhbXBsZS9hcGkvdXNlci92MTt1c2VydjGiAgNVWFiqAgdVc2VyLlYxygIHVXNlclxWMeICE1VzZXJcVjFcR1BCTWV0YWRhdGHqAghVc2VyOjpWMWIGcHJvdG8z");

/**
 * @generated from message user.v1.SignInRequest
 */
export type SignInRequest = Message<"user.v1.SignInRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;
};

/**
 * Describes the message user.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 0);

/**
 * @generated from message user.v1.SignInResponse
 */
export type SignInResponse = Message<"user.v1.SignInResponse"> & {
  /**
   * @generated from field: string state = 1;
   */
  state: string;

  /**
   * @generated from field: string data = 2;
   */
  data: string;
};

/**
 * Describes the message user.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema: GenMessage<SignInResponse> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 1);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_user_v1_user, 0);

