# curl -v -X POST http://my.app.com/check.v1.CheckService/Ready
#  --header 'Content-Type: application/json'
#  --data-raw '{}'
POST http://localhost:4000/user.v1.UserService/SayHello
Content-Type: application/json

{}
